import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { gql } from '@apollo/client';
import client from '../gql/config';

const ALL_USERS = gql`
  query {
    getUsers {
      id
      name
      email
    }
  }
`;

export default function Home({ users }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        {users.map((user) => (
          <h1 key={user.id}>
            {user.name} - {user.email}
          </h1>
        ))}
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const { data } = await client.query({
    query: ALL_USERS,
  });

  const users = data.getUsers;

  return {
    props: {
      users,
    },
  };
}
